data_dir: data
preprocess_data: false
goal: null
eval: null
log_dir: logs
workspace_dir: workspaces
copy_data: true
exp_name: run
exec:
  timeout: 600
  agent_file_name: runfile.py
  format_tb_ipython: false
generate_report: true
report:
  model: gpt-4o-2024-11-20
  temp: 1.0
experiment:
  num_syn_datasets: 1
debug:
  stage4: false
agent:
  type: parallel
  num_workers: 1
  stages:
    stage1_max_iters: 4
    stage2_max_iters: 3
    stage3_max_iters: 3
    stage4_max_iters: 4
  steps: 3
  k_fold_validation: 1
  multi_seed_eval:
    num_seeds: 1
  expose_prediction: false
  data_preview: false
  code:
    model: gpt-4o-mini-2024-07-18
    temp: 1.0
    max_tokens: 12000
  feedback:
    model: gpt-4o-mini-2024-07-18
    temp: 0.5
    max_tokens: 8192
  vlm_feedback:
    model: gpt-4o-mini-2024-07-18
    temp: 0.5
    max_tokens: null
  search:
    max_debug_depth: 3
    debug_prob: 0.5
    num_drafts: 1
